Practice/TuNTCHE176697.NWEB.Practice.T04/LeavaManagement.API/LeaveManagement.Web/Controllers/LeaveController.cs
using Azure.Core;
using LeaveManagement.BusinessLayer.DTO;
using LeaveManagement.DataLayer.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;

namespace LeaveManagement.Web.Controllers
{
    public class LeaveController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7295/api");
        private readonly HttpClient _httpClient;

        public LeaveController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
        }
        public async Task<IActionResult> Login(UserLogin user)
        {
            StringContent content = new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8, "application/json");
            var reponse = await _httpClient.PostAsync(baseAddress + "/Auth/Login", content);
            string token = await reponse.Content.ReadAsStringAsync();
            if (token == "Account not found!")
            {
                ViewBag.Message = "Incorrect Email or Password!";
                return View("Index");
            }

            var handler = new JwtSecurityTokenHandler();
            var jsonToken = handler.ReadToken(token) as JwtSecurityToken;
            string userId = jsonToken.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;
            string userName = jsonToken.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
            string userRole = jsonToken.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;


            HttpContext.Session.SetString("JWToken", token);
            HttpContext.Session.SetString("UserId", userId);
            HttpContext.Session.SetString("UserName", userName);
            HttpContext.Session.SetString("UserRole", userRole);

            ViewBag.Ursername = HttpContext.Session.GetString("UserName");
            return RedirectToAction("Main");

        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Main()
        {
            var role = HttpContext.Session.GetString("UserRole");
            var id = HttpContext.Session.GetString("UserId");
            var token = HttpContext.Session.GetString("JWToken");

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            List<RequestViewModel> list = new List<RequestViewModel>();
            if (role == "Admin")
            {
                HttpResponseMessage response = _httpClient.GetAsync(baseAddress + "/AdminLeaveManagement/GetAllRequests").Result;
                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    list = JsonConvert.DeserializeObject<List<RequestViewModel>>(data);
                    return View(list);
                }
                else return RedirectToAction("AccessDenied");
            }
            if (role == "Student")
            {
                HttpResponseMessage response = _httpClient.GetAsync(baseAddress + "/StudentLeaveManagement/GetAllRequestByStudentID/" + Guid.Parse(id)).Result;
                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    list = JsonConvert.DeserializeObject<List<RequestViewModel>>(data);
                    return View(list);
                }
                else return RedirectToAction("AccessDenied");
            }
            return RedirectToAction("AccessDenied");
        }

        [HttpGet]
        public IActionResult Manage()
        {
            var role = HttpContext.Session.GetString("UserRole");
            var token = HttpContext.Session.GetString("JWToken");

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            List<RequestViewModel> list = new List<RequestViewModel>();
            if (role == "Admin")
            {
                HttpResponseMessage response = _httpClient.GetAsync(baseAddress + "/AdminLeaveManagement/GetSumittedRequests").Result;
                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    list = JsonConvert.DeserializeObject<List<RequestViewModel>>(data);
                    return View(list);
                }
                else return RedirectToAction("AccessDenied");
            }           
            return RedirectToAction("AccessDenied");
        }
        [HttpGet]
        public IActionResult Create()
        {
            var token = HttpContext.Session.GetString("JWToken");
            var role = HttpContext.Session.GetString("UserRole");
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            List<Group> list = new List<Group>();
            if (role == "Student")
            {
                HttpResponseMessage response1 = _httpClient.GetAsync(baseAddress + "/StudentLeaveManagement/GetAllClass").Result;
                if (response1.IsSuccessStatusCode)
                {
                    string data1 = response1.Content.ReadAsStringAsync().Result;
                    list = JsonConvert.DeserializeObject<List<Group>>(data1);
                }
                IEnumerable<SelectListItem> classList = list.Select(u => new SelectListItem
                {
                    Text = "Class " + u.GroupName,
                    Value = u.GroupId.ToString(),
                }
                );
                ViewBag.ClassRoom = classList;

                return View();
            }
            else return RedirectToAction("AccessDenied");
        }
        [HttpPost]
        public IActionResult Create(RequestDTO request)
        {
            var token = HttpContext.Session.GetString("JWToken");
            var role = HttpContext.Session.GetString("UserRole");
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            
            try
            {
                if (role == "Student")
                {
                    var id = HttpContext.Session.GetString("UserId");
                    request.AccountID = Guid.Parse(id);
                    request.RequestID = Guid.NewGuid();
                    string data = JsonConvert.SerializeObject(request);
                    StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                    HttpResponseMessage response = _httpClient.PostAsync(baseAddress + "/StudentLeaveManagement/CreateRequest", content).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["success"] = "Created";
                        return RedirectToAction("Main");
                    }
                    else return RedirectToAction("AccessDenied");
                }
                else return RedirectToAction("AccessDenied");
            }
            catch (Exception ex)
            {     
                return View();
            }
           }

        [HttpGet]
        public IActionResult ViewDetail(Guid id)
        {
            var role = HttpContext.Session.GetString("UserRole");
            var token = HttpContext.Session.GetString("JWToken");

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            RequestDTO requestDetail = new RequestDTO();
            try
            {
                if (role == "Admin")
                {
                    HttpResponseMessage response = _httpClient.GetAsync(baseAddress + "/AdminLeaveManagement/GetRequestByID/" + id).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        string data = response.Content.ReadAsStringAsync().Result;
                        requestDetail = JsonConvert.DeserializeObject<RequestDTO>(data);

                    }
                    return View(requestDetail);
                }
                if (role == "Student")
                {
                    HttpResponseMessage response = _httpClient.GetAsync(baseAddress + "/StudentLeaveManagement/GetRequestByID/" + id).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        string data = response.Content.ReadAsStringAsync().Result;
                        requestDetail = JsonConvert.DeserializeObject<RequestDTO>(data);

                    }
                    return View(requestDetail);
                }
                return RedirectToAction("AccessDenied");

            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        
        public IActionResult Cancel(Guid requestID)
        {
            var token = HttpContext.Session.GetString("JWToken");
            var role = HttpContext.Session.GetString("UserRole");
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            try
            {
                if (role == "Student")
                {
                    string data = JsonConvert.SerializeObject(requestID);
                    StringContent content = new StringContent(data, Encoding.UTF8, "application/json");

Practice/TuNTCHE176697.NWEB.Practice.T04/LeavaManagement.API/LeaveManagement.Web/Views/Leave/Create.cshtml
@using LeaveManagement.DataLayer.Enum;
@model RequestDTO

<form asp-action="Create">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h1 class="text-dark text-center">Create Leave Request</h1>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="StudentName" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10">
                <input asp-for="StudentName" class="form-control" />
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="GroupID" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10">
                <select asp-for="GroupID" asp-items="ViewBag.ClassRoom" class="form-select">
                    <option disabled selected>--Select Class---</option>
                </select>
                <span asp-validation-for="GroupID" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Title" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="LeaveDate" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10">
                <input type="date" asp-for="LeaveDate" class="form-control" />
                <span asp-validation-for="LeaveDate" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row p-1 ">
            <label asp-for="LeaveType" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10 ">
            @foreach (var item in Html.GetEnumSelectList<LeaveType>())
            {
                <input  type="radio" asp-for="LeaveType" value="@item.Value"  >
                @item.Text
                <br />
            }
            <span asp-validation-for="LeaveType" class="text-danger"></span>
      </div>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Reason" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10">
                <textarea asp-for="Reason" class="form-control" rows="2"></textarea>
                
            </div>
        </div>
        <div class="text-end">
            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-controller="Leave" asp-action="Main" class="btn btn-primary">Back</a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Practice/TuNTCHE176697.NWEB.Practice.T04/LeavaManagement.API/LeaveManagement.Web/Views/Leave/Edit.cshtml
@using LeaveManagement.DataLayer.Enum;
@model RequestDTO

<form asp-action="Edit">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h1 class="text-dark text-center">Edit Request</h1>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="StudentName" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10">
                <input asp-for="StudentName" class="form-control" />
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="GroupID" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10">
                <select asp-for="GroupID" asp-items="ViewBag.ClassRoom" class="form-select">
                    <option disabled selected>--Select Class---</option>
                </select>
                <span asp-validation-for="GroupID" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Title" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="LeaveDate" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10">
                <input type="date" asp-for="LeaveDate" class="form-control" />
                <span asp-validation-for="LeaveDate" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="LeaveType" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10 ">
                @foreach (var item in Html.GetEnumSelectList<LeaveType>())
                {
                    <input type="radio" asp-for="LeaveType" value="@item.Value" checked="@Model.LeaveType == item.Value">
                    @item.Text
                    <br />
                }
                <span asp-validation-for="LeaveType" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Reason" class="p-0 col-sm-2 text-end fw-bold"></label>
            <div class="col-sm-10">
                <textarea asp-for="Reason" class="form-control" rows="2"></textarea>
            
            </div>
        </div>
        <input type="hidden" asp-for="RequestID" />
        <div class="text-end">
            <button type="submit" class="btn btn-primary">Save Change</button>
            <a asp-controller="Leave" asp-action="Main" class="btn btn-primary">Back</a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Practice/TuNTCHE176697.NWEB.Practice.T04/LeavaManagement.API/LeaveManagement.Web/Views/Leave/Index.cshtml
@model UserLogin

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
<div class="container h-100">
	<div class="row justify-content-sm-center h-100">
		<div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
			<div class="text-center my-5">
				
			</div>
			<div class="card shadow-lg">
				<div class="card-body p-5">
					<h1 class="fs-4 card-title fw-bold mb-4">Login</h1>
					<form asp-action="Login" class="needs-validation" novalidate="" autocomplete="off">
						<div class="mb-3">
							<label asp-for="Email" class="mb-2 text-muted"></label>
							<input asp-for="Email" class="form-control" required autofocus>
							<span asp-validation-for="Email" class="text-danger"></span>
						</div>
						<div class="mb-3">
							<div class="mb-2 w-100">
								<label asp-for="Password"  class="text-muted">Password</label>
							</div>
							<input asp-for="Password" type="password" class="form-control" required>
							<span asp-validation-for="Password" class="text-danger"></span>
						</div>
						<div class="d-flex align-items-center">
							<button type="submit" class="btn btn-primary ms-auto w-100">
								Login
							</button>
						</div>
					</form>
				</div>
				<div class="card-footer py-3 border-0">
					<div class="text-center">
						Don't have an account? <a asp-action="Index" class="text-dark">Create One</a>
					</div>
				</div>
			</div>
			<div class="text-center mt-5 text-muted">
				Copyright &copy; 2017-2021 &mdash; Your Company
			</div>
		</div>
	</div>
</div>

Practice/TuNTCHE176697.NWEB.Practice.T04/LeavaManagement.API/LeaveManagement.Web/Views/Leave/Main.cshtml
@model IEnumerable<LeaveManagement.BusinessLayer.DTO.RequestViewModel>

@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    var role = @HttpContextAccessor.HttpContext.Session.GetString("UserRole");
}

<div class="p-3 mt-4">
    <div class="row pb-4">
        <h1 class="text-dark text-center">View Request</h1>
    </div>
    @if(role == "Student"){
    
        <div class="text-end mb-2">
            <a asp-controller="Leave" asp-action="Create" class="btn btn-primary">Create Request</a>
        </div>
    }
    
    <table class="table">
        <thead>
            <tr class="table-primary border-1">
                <th>Student Name</th>
                <th>Class Name</th>
                <th>Title</th>
                <th>Leave Date</th>
                <th>Leave Type</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td><a asp-controller="Leave" asp-action="ViewDetail" asp-route-id="@obj.RequestID">@obj.StudentName</a></td>
                    <td>Class @obj.ClassName</td>
                    <td>@obj.Title</td>
                    <td>@obj.LeaveDate.ToShortDateString()</td>
                    <td>@obj.LeaveType</td>
                    <td>@obj.LeaveStatus</td>
                </tr>
            }
        </tbody>
    </table>
</div>
        

Practice/TuNTCHE176697.NWEB.Practice.T04/LeavaManagement.API/LeaveManagement.Web/Views/Leave/Manage.cshtml
@model IEnumerable<LeaveManagement.BusinessLayer.DTO.RequestViewModel>

<div class="p-3 mt-4">
    <div class="row pb-4">
        <h1 class="text-dark text-center">Manage Request</h1>
    </div>

    <table class="table">
        <thead>
            <tr class="table-primary border-1">
                <th>Student Name</th>
                <th>Class Name</th>
                <th>Title</th>
                <th>Leave Date</th>
                <th>Leave Type</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td><a asp-controller="Leave" asp-action="ViewDetail" asp-route-id="@obj.RequestID">@obj.StudentName</a></td>
                    <td>Class @obj.ClassName</td>
                    <td>@obj.Title</td>
                    <td>@obj.LeaveDate.ToShortDateString()</td>
                    <td>@obj.LeaveType</td>
                    <td>@obj.LeaveStatus</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Practice/TuNTCHE176697.NWEB.Practice.T04/LeavaManagement.API/LeaveManagement.Web/Views/Leave/ViewDetail.cshtml
@model LeaveManagement.BusinessLayer.DTO.RequestDTO

@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    var role = @HttpContextAccessor.HttpContext.Session.GetString("UserRole");
}
@{
    ViewData["Title"] = "ViewDetail";
    
}

<div class="p-3 mt-4">
    <div class="row pb-4">
        <h1 class="text-dark text-center">Detail Request</h1>
    </div>
    <div>
        <div class="row">
            <div class="col-md-2">
                <p class="fw-bold text-end">Student Name</p>
            </div>
            <div class="col-md-10">
                <p>@Model.StudentName</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <p class="fw-bold text-end">Class Name</p>
            </div>
            <div class="col-md-10">
                <p>@Model.GroupName</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <p class="fw-bold text-end">Title</p>
            </div>
            <div class="col-md-10">
                <p>@Model.Title</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <p class="fw-bold text-end">Leave Date</p>
            </div>
            <div class="col-md-10">
                <p>@Model.LeaveDate</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <p class="fw-bold text-end">Leave Type</p>
            </div>
            <div class="col-md-10">
                <p>@Model.LeaveType</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <p class="fw-bold text-end">Reason for leave</p>
            </div>
            <div class="col-md-10">
                <p>@Model.Reason</p>
            </div>
        </div>
        <div class="text-end mt-3">
            @if(role == "Admin")
            {
                @if (Model.Status == "Submitted")
                {

                    <a asp-controller="Leave" asp-action="Approve" asp-route-requestID="@Model.RequestID" class="btn btn-success">Approve</a>
                    <a asp-controller="Leave" asp-action="Reject" asp-route-requestID="@Model.RequestID" class="btn btn-danger">Reject</a>
                }
            }
            @if(role == "Student")
            {
                @if (Model.Status == "Submitted")
                {
                    <a asp-controller="Leave" asp-action="Edit" asp-route-requestID="@Model.RequestID" class="btn btn-warning">Edit</a>
                    <a asp-controller="Leave" asp-action="Cancel" asp-route-requestID="@Model.RequestID" class="btn btn-danger">Cancel</a>
                }
            }

            <a asp-controller="Leave" asp-action="Main" class="btn btn-primary">Back</a>
        </div>
    </div>
</div>